# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.zonage_sismique_api import ZonageSismiqueApi  # noqa: E501
from swagger_client.rest import ApiException


class TestZonageSismiqueApi(unittest.TestCase):
    """ZonageSismiqueApi unit test stubs"""

    def setUp(self):
        self.api = ZonageSismiqueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recherche_radon(self):
        """Test case for recherche_radon

        Lister les zonages sismiques  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
