# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cavites_api import CavitesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCavitesApi(unittest.TestCase):
    """CavitesApi unit test stubs"""

    def setUp(self):
        self.api = CavitesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recherche_risques8(self):
        """Test case for recherche_risques8

        Cette interface est conçue pour diffuser les données sur les cavités souterraines.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
