# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ssp import Ssp  # noqa: E501
from swagger_client.rest import ApiException


class TestSsp(unittest.TestCase):
    """Ssp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSsp(self):
        """Test Ssp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ssp.Ssp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
