# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.multi_point import MultiPoint  # noqa: E501
from swagger_client.rest import ApiException


class TestMultiPoint(unittest.TestCase):
    """MultiPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiPoint(self):
        """Test MultiPoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.multi_point.MultiPoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
