# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.risques_api import RisquesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRisquesApi(unittest.TestCase):
    """RisquesApi unit test stubs"""

    def setUp(self):
        self.api = RisquesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recherche_risques4(self):
        """Test case for recherche_risques4

        Lister les types de risques recensés sur le territoire concerné  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
