# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dicrim_api import DICRIMApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDICRIMApi(unittest.TestCase):
    """DICRIMApi unit test stubs"""

    def setUp(self):
        self.api = DICRIMApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recherche_risques6(self):
        """Test case for recherche_risques6

        Lister les Documents d'Information Communale sur les Risques Majeurs (DICRIM) sur le territoire concerné  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
