# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.zonage_sismique import ZonageSismique  # noqa: E501
from swagger_client.rest import ApiException


class TestZonageSismique(unittest.TestCase):
    """ZonageSismique unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZonageSismique(self):
        """Test ZonageSismique"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.zonage_sismique.ZonageSismique()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
