# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.multi_line_string import MultiLineString  # noqa: E501
from swagger_client.rest import ApiException


class TestMultiLineString(unittest.TestCase):
    """MultiLineString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiLineString(self):
        """Test MultiLineString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.multi_line_string.MultiLineString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
