# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.retrait_gonflement_des_argiles_api import RetraitGonflementDesArgilesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRetraitGonflementDesArgilesApi(unittest.TestCase):
    """RetraitGonflementDesArgilesApi unit test stubs"""

    def setUp(self):
        self.api = RetraitGonflementDesArgilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rechercher_zonage_retrait_gonflement(self):
        """Test case for rechercher_zonage_retrait_gonflement

        Cette interface est conçue pour diffuser les données sur le retrait / gonflement des sols argileux.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
