# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_sis_dto_geom import OneOfSisDtoGeom  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfSisDtoGeom(unittest.TestCase):
    """OneOfSisDtoGeom unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfSisDtoGeom(self):
        """Test OneOfSisDtoGeom"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_sis_dto_geom.OneOfSisDtoGeom()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
