# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ssp_api import SSPApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSSPApi(unittest.TestCase):
    """SSPApi unit test stubs"""

    def setUp(self):
        self.api = SSPApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recherche_casias(self):
        """Test case for recherche_casias

        Lister les Cartes des Anciens Sites Industriels et Activités de Services  # noqa: E501
        """
        pass

    def test_recherche_ex_basol(self):
        """Test case for recherche_ex_basol

        Lister les informations de l'administration concernant une pollution suspectée ou avérée (ex-BASOL)  # noqa: E501
        """
        pass

    def test_recherche_globale(self):
        """Test case for recherche_globale

        Lister les données CASIAS, ex-BASOL, SIS et SUP.  # noqa: E501
        """
        pass

    def test_recherche_sis(self):
        """Test case for recherche_sis

        Lister les Secteurs d'Information sur les Sols  # noqa: E501
        """
        pass

    def test_recherche_sup(self):
        """Test case for recherche_sup

        Lister les Servitudes d'Utilité Publique  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
