# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.risques_technologiques_dto import RisquesTechnologiquesDto  # noqa: E501
from swagger_client.rest import ApiException


class TestRisquesTechnologiquesDto(unittest.TestCase):
    """RisquesTechnologiquesDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRisquesTechnologiquesDto(self):
        """Test RisquesTechnologiquesDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.risques_technologiques_dto.RisquesTechnologiquesDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
