# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tri import Tri  # noqa: E501
from swagger_client.rest import ApiException


class TestTri(unittest.TestCase):
    """Tri unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTri(self):
        """Test Tri"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tri.Tri()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
