# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.paginated_response_ex_basol_dto import PaginatedResponseExBasolDto  # noqa: E501
from swagger_client.rest import ApiException


class TestPaginatedResponseExBasolDto(unittest.TestCase):
    """PaginatedResponseExBasolDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedResponseExBasolDto(self):
        """Test PaginatedResponseExBasolDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.paginated_response_ex_basol_dto.PaginatedResponseExBasolDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
