# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.rapport_risques_json_dto import RapportRisquesJsonDto  # noqa: E501
from swagger_client.rest import ApiException


class TestRapportRisquesJsonDto(unittest.TestCase):
    """RapportRisquesJsonDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRapportRisquesJsonDto(self):
        """Test RapportRisquesJsonDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.rapport_risques_json_dto.RapportRisquesJsonDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
