# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rapport_pdf_et_json_api import RapportPDFEtJSONApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRapportPDFEtJSONApi(unittest.TestCase):
    """RapportPDFEtJSONApi unit test stubs"""

    def setUp(self):
        self.api = RapportPDFEtJSONApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_rapport_risque(self):
        """Test case for generate_rapport_risque

        Cette interface est conçue pour generer un rapport de risque : adresse ou latlon génèrent un rapport à l'adresse. code_insee génère un rapport à la commune.  # noqa: E501
        """
        pass

    def test_generate_rapport_risque_json(self):
        """Test case for generate_rapport_risque_json

        Résultats du rapport des risques près de chez moi  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
