# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.installations_classes_api import InstallationsClassesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInstallationsClassesApi(unittest.TestCase):
    """InstallationsClassesApi unit test stubs"""

    def setUp(self):
        self.api = InstallationsClassesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rechercher_aiots_par_geolocalisation(self):
        """Test case for rechercher_aiots_par_geolocalisation

        Cette interface est conçue pour diffuser les données installations classées de Gun Env à destination de Géorisques.  # noqa: E501
        """
        pass

    def test_rechercher_aiots_par_geolocalisation1(self):
        """Test case for rechercher_aiots_par_geolocalisation1

        Cette interface est conçue pour diffuser les données installations classées de Gun Env à destination de Géorisques.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
