# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.catnat_api import CATNATApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCATNATApi(unittest.TestCase):
    """CATNATApi unit test stubs"""

    def setUp(self):
        self.api = CATNATApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recherche_cat_nat(self):
        """Test case for recherche_cat_nat

        Lister les arrêtés de catastrophe naturelle  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
