# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AdresseDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'libelle': 'str',
        'longitude': 'float',
        'latitude': 'float'
    }

    attribute_map = {
        'libelle': 'libelle',
        'longitude': 'longitude',
        'latitude': 'latitude'
    }

    def __init__(self, libelle=None, longitude=None, latitude=None):  # noqa: E501
        """AdresseDto - a model defined in Swagger"""  # noqa: E501
        self._libelle = None
        self._longitude = None
        self._latitude = None
        self.discriminator = None
        if libelle is not None:
            self.libelle = libelle
        if longitude is not None:
            self.longitude = longitude
        if latitude is not None:
            self.latitude = latitude

    @property
    def libelle(self):
        """Gets the libelle of this AdresseDto.  # noqa: E501


        :return: The libelle of this AdresseDto.  # noqa: E501
        :rtype: str
        """
        return self._libelle

    @libelle.setter
    def libelle(self, libelle):
        """Sets the libelle of this AdresseDto.


        :param libelle: The libelle of this AdresseDto.  # noqa: E501
        :type: str
        """

        self._libelle = libelle

    @property
    def longitude(self):
        """Gets the longitude of this AdresseDto.  # noqa: E501


        :return: The longitude of this AdresseDto.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this AdresseDto.


        :param longitude: The longitude of this AdresseDto.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def latitude(self):
        """Gets the latitude of this AdresseDto.  # noqa: E501


        :return: The latitude of this AdresseDto.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this AdresseDto.


        :param latitude: The latitude of this AdresseDto.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdresseDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdresseDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
