# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Azi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code_national_azi': 'str',
        'libelle_azi': 'str',
        'liste_libelle_risque': 'list[RisqueGaspar]',
        'libelle_bassin_risques': 'str',
        'date_debut_programmation': 'date',
        'date_fin_programmation': 'date',
        'date_debut_etude': 'date',
        'date_fin_etude': 'date',
        'date_debut_information': 'date',
        'date_fin_information': 'date',
        'date_realisation': 'date',
        'date_diffusion': 'date',
        'date_publication_web': 'date',
        'code_insee': 'str',
        'libelle_commune': 'str'
    }

    attribute_map = {
        'code_national_azi': 'code_national_azi',
        'libelle_azi': 'libelle_azi',
        'liste_libelle_risque': 'liste_libelle_risque',
        'libelle_bassin_risques': 'libelle_bassin_risques',
        'date_debut_programmation': 'date_debut_programmation',
        'date_fin_programmation': 'date_fin_programmation',
        'date_debut_etude': 'date_debut_etude',
        'date_fin_etude': 'date_fin_etude',
        'date_debut_information': 'date_debut_information',
        'date_fin_information': 'date_fin_information',
        'date_realisation': 'date_realisation',
        'date_diffusion': 'date_diffusion',
        'date_publication_web': 'date_publication_web',
        'code_insee': 'code_insee',
        'libelle_commune': 'libelle_commune'
    }

    def __init__(self, code_national_azi=None, libelle_azi=None, liste_libelle_risque=None, libelle_bassin_risques=None, date_debut_programmation=None, date_fin_programmation=None, date_debut_etude=None, date_fin_etude=None, date_debut_information=None, date_fin_information=None, date_realisation=None, date_diffusion=None, date_publication_web=None, code_insee=None, libelle_commune=None):  # noqa: E501
        """Azi - a model defined in Swagger"""  # noqa: E501
        self._code_national_azi = None
        self._libelle_azi = None
        self._liste_libelle_risque = None
        self._libelle_bassin_risques = None
        self._date_debut_programmation = None
        self._date_fin_programmation = None
        self._date_debut_etude = None
        self._date_fin_etude = None
        self._date_debut_information = None
        self._date_fin_information = None
        self._date_realisation = None
        self._date_diffusion = None
        self._date_publication_web = None
        self._code_insee = None
        self._libelle_commune = None
        self.discriminator = None
        if code_national_azi is not None:
            self.code_national_azi = code_national_azi
        if libelle_azi is not None:
            self.libelle_azi = libelle_azi
        if liste_libelle_risque is not None:
            self.liste_libelle_risque = liste_libelle_risque
        if libelle_bassin_risques is not None:
            self.libelle_bassin_risques = libelle_bassin_risques
        if date_debut_programmation is not None:
            self.date_debut_programmation = date_debut_programmation
        if date_fin_programmation is not None:
            self.date_fin_programmation = date_fin_programmation
        if date_debut_etude is not None:
            self.date_debut_etude = date_debut_etude
        if date_fin_etude is not None:
            self.date_fin_etude = date_fin_etude
        if date_debut_information is not None:
            self.date_debut_information = date_debut_information
        if date_fin_information is not None:
            self.date_fin_information = date_fin_information
        if date_realisation is not None:
            self.date_realisation = date_realisation
        if date_diffusion is not None:
            self.date_diffusion = date_diffusion
        if date_publication_web is not None:
            self.date_publication_web = date_publication_web
        if code_insee is not None:
            self.code_insee = code_insee
        if libelle_commune is not None:
            self.libelle_commune = libelle_commune

    @property
    def code_national_azi(self):
        """Gets the code_national_azi of this Azi.  # noqa: E501

        Identifiant unique de l'AZI  # noqa: E501

        :return: The code_national_azi of this Azi.  # noqa: E501
        :rtype: str
        """
        return self._code_national_azi

    @code_national_azi.setter
    def code_national_azi(self, code_national_azi):
        """Sets the code_national_azi of this Azi.

        Identifiant unique de l'AZI  # noqa: E501

        :param code_national_azi: The code_national_azi of this Azi.  # noqa: E501
        :type: str
        """

        self._code_national_azi = code_national_azi

    @property
    def libelle_azi(self):
        """Gets the libelle_azi of this Azi.  # noqa: E501

        Libellé de l'AZI  # noqa: E501

        :return: The libelle_azi of this Azi.  # noqa: E501
        :rtype: str
        """
        return self._libelle_azi

    @libelle_azi.setter
    def libelle_azi(self, libelle_azi):
        """Sets the libelle_azi of this Azi.

        Libellé de l'AZI  # noqa: E501

        :param libelle_azi: The libelle_azi of this Azi.  # noqa: E501
        :type: str
        """

        self._libelle_azi = libelle_azi

    @property
    def liste_libelle_risque(self):
        """Gets the liste_libelle_risque of this Azi.  # noqa: E501

        Détail du risque gaspar  # noqa: E501

        :return: The liste_libelle_risque of this Azi.  # noqa: E501
        :rtype: list[RisqueGaspar]
        """
        return self._liste_libelle_risque

    @liste_libelle_risque.setter
    def liste_libelle_risque(self, liste_libelle_risque):
        """Sets the liste_libelle_risque of this Azi.

        Détail du risque gaspar  # noqa: E501

        :param liste_libelle_risque: The liste_libelle_risque of this Azi.  # noqa: E501
        :type: list[RisqueGaspar]
        """

        self._liste_libelle_risque = liste_libelle_risque

    @property
    def libelle_bassin_risques(self):
        """Gets the libelle_bassin_risques of this Azi.  # noqa: E501

        Libellé bassin de risque  # noqa: E501

        :return: The libelle_bassin_risques of this Azi.  # noqa: E501
        :rtype: str
        """
        return self._libelle_bassin_risques

    @libelle_bassin_risques.setter
    def libelle_bassin_risques(self, libelle_bassin_risques):
        """Sets the libelle_bassin_risques of this Azi.

        Libellé bassin de risque  # noqa: E501

        :param libelle_bassin_risques: The libelle_bassin_risques of this Azi.  # noqa: E501
        :type: str
        """

        self._libelle_bassin_risques = libelle_bassin_risques

    @property
    def date_debut_programmation(self):
        """Gets the date_debut_programmation of this Azi.  # noqa: E501

        Date de début de programmation  # noqa: E501

        :return: The date_debut_programmation of this Azi.  # noqa: E501
        :rtype: date
        """
        return self._date_debut_programmation

    @date_debut_programmation.setter
    def date_debut_programmation(self, date_debut_programmation):
        """Sets the date_debut_programmation of this Azi.

        Date de début de programmation  # noqa: E501

        :param date_debut_programmation: The date_debut_programmation of this Azi.  # noqa: E501
        :type: date
        """

        self._date_debut_programmation = date_debut_programmation

    @property
    def date_fin_programmation(self):
        """Gets the date_fin_programmation of this Azi.  # noqa: E501

        Date de fin de programmation  # noqa: E501

        :return: The date_fin_programmation of this Azi.  # noqa: E501
        :rtype: date
        """
        return self._date_fin_programmation

    @date_fin_programmation.setter
    def date_fin_programmation(self, date_fin_programmation):
        """Sets the date_fin_programmation of this Azi.

        Date de fin de programmation  # noqa: E501

        :param date_fin_programmation: The date_fin_programmation of this Azi.  # noqa: E501
        :type: date
        """

        self._date_fin_programmation = date_fin_programmation

    @property
    def date_debut_etude(self):
        """Gets the date_debut_etude of this Azi.  # noqa: E501

        Date de début de l'étude  # noqa: E501

        :return: The date_debut_etude of this Azi.  # noqa: E501
        :rtype: date
        """
        return self._date_debut_etude

    @date_debut_etude.setter
    def date_debut_etude(self, date_debut_etude):
        """Sets the date_debut_etude of this Azi.

        Date de début de l'étude  # noqa: E501

        :param date_debut_etude: The date_debut_etude of this Azi.  # noqa: E501
        :type: date
        """

        self._date_debut_etude = date_debut_etude

    @property
    def date_fin_etude(self):
        """Gets the date_fin_etude of this Azi.  # noqa: E501

        Date de fin de l'étude  # noqa: E501

        :return: The date_fin_etude of this Azi.  # noqa: E501
        :rtype: date
        """
        return self._date_fin_etude

    @date_fin_etude.setter
    def date_fin_etude(self, date_fin_etude):
        """Sets the date_fin_etude of this Azi.

        Date de fin de l'étude  # noqa: E501

        :param date_fin_etude: The date_fin_etude of this Azi.  # noqa: E501
        :type: date
        """

        self._date_fin_etude = date_fin_etude

    @property
    def date_debut_information(self):
        """Gets the date_debut_information of this Azi.  # noqa: E501

        Date de début d'information  # noqa: E501

        :return: The date_debut_information of this Azi.  # noqa: E501
        :rtype: date
        """
        return self._date_debut_information

    @date_debut_information.setter
    def date_debut_information(self, date_debut_information):
        """Sets the date_debut_information of this Azi.

        Date de début d'information  # noqa: E501

        :param date_debut_information: The date_debut_information of this Azi.  # noqa: E501
        :type: date
        """

        self._date_debut_information = date_debut_information

    @property
    def date_fin_information(self):
        """Gets the date_fin_information of this Azi.  # noqa: E501

        Date de fin d'information  # noqa: E501

        :return: The date_fin_information of this Azi.  # noqa: E501
        :rtype: date
        """
        return self._date_fin_information

    @date_fin_information.setter
    def date_fin_information(self, date_fin_information):
        """Sets the date_fin_information of this Azi.

        Date de fin d'information  # noqa: E501

        :param date_fin_information: The date_fin_information of this Azi.  # noqa: E501
        :type: date
        """

        self._date_fin_information = date_fin_information

    @property
    def date_realisation(self):
        """Gets the date_realisation of this Azi.  # noqa: E501

        Date de réalisation  # noqa: E501

        :return: The date_realisation of this Azi.  # noqa: E501
        :rtype: date
        """
        return self._date_realisation

    @date_realisation.setter
    def date_realisation(self, date_realisation):
        """Sets the date_realisation of this Azi.

        Date de réalisation  # noqa: E501

        :param date_realisation: The date_realisation of this Azi.  # noqa: E501
        :type: date
        """

        self._date_realisation = date_realisation

    @property
    def date_diffusion(self):
        """Gets the date_diffusion of this Azi.  # noqa: E501

        Date de diffusion  # noqa: E501

        :return: The date_diffusion of this Azi.  # noqa: E501
        :rtype: date
        """
        return self._date_diffusion

    @date_diffusion.setter
    def date_diffusion(self, date_diffusion):
        """Sets the date_diffusion of this Azi.

        Date de diffusion  # noqa: E501

        :param date_diffusion: The date_diffusion of this Azi.  # noqa: E501
        :type: date
        """

        self._date_diffusion = date_diffusion

    @property
    def date_publication_web(self):
        """Gets the date_publication_web of this Azi.  # noqa: E501

        Date de publication web  # noqa: E501

        :return: The date_publication_web of this Azi.  # noqa: E501
        :rtype: date
        """
        return self._date_publication_web

    @date_publication_web.setter
    def date_publication_web(self, date_publication_web):
        """Sets the date_publication_web of this Azi.

        Date de publication web  # noqa: E501

        :param date_publication_web: The date_publication_web of this Azi.  # noqa: E501
        :type: date
        """

        self._date_publication_web = date_publication_web

    @property
    def code_insee(self):
        """Gets the code_insee of this Azi.  # noqa: E501

        Identifiant unique INSEE de la commune  # noqa: E501

        :return: The code_insee of this Azi.  # noqa: E501
        :rtype: str
        """
        return self._code_insee

    @code_insee.setter
    def code_insee(self, code_insee):
        """Sets the code_insee of this Azi.

        Identifiant unique INSEE de la commune  # noqa: E501

        :param code_insee: The code_insee of this Azi.  # noqa: E501
        :type: str
        """

        self._code_insee = code_insee

    @property
    def libelle_commune(self):
        """Gets the libelle_commune of this Azi.  # noqa: E501

        Libellé de la commune  # noqa: E501

        :return: The libelle_commune of this Azi.  # noqa: E501
        :rtype: str
        """
        return self._libelle_commune

    @libelle_commune.setter
    def libelle_commune(self, libelle_commune):
        """Sets the libelle_commune of this Azi.

        Libellé de la commune  # noqa: E501

        :param libelle_commune: The libelle_commune of this Azi.  # noqa: E501
        :type: str
        """

        self._libelle_commune = libelle_commune

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Azi, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Azi):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
