# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Cavites(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'identifiant': 'str',
        'type': 'str',
        'nom': 'str',
        'reperage_geo': 'str',
        'region': 'Region',
        'departement': 'Departement',
        'code_insee': 'str',
        'longitude': 'float',
        'latitude': 'float'
    }

    attribute_map = {
        'identifiant': 'identifiant',
        'type': 'type',
        'nom': 'nom',
        'reperage_geo': 'reperage_geo',
        'region': 'region',
        'departement': 'departement',
        'code_insee': 'code_insee',
        'longitude': 'longitude',
        'latitude': 'latitude'
    }

    def __init__(self, identifiant=None, type=None, nom=None, reperage_geo=None, region=None, departement=None, code_insee=None, longitude=None, latitude=None):  # noqa: E501
        """Cavites - a model defined in Swagger"""  # noqa: E501
        self._identifiant = None
        self._type = None
        self._nom = None
        self._reperage_geo = None
        self._region = None
        self._departement = None
        self._code_insee = None
        self._longitude = None
        self._latitude = None
        self.discriminator = None
        if identifiant is not None:
            self.identifiant = identifiant
        if type is not None:
            self.type = type
        if nom is not None:
            self.nom = nom
        if reperage_geo is not None:
            self.reperage_geo = reperage_geo
        if region is not None:
            self.region = region
        if departement is not None:
            self.departement = departement
        if code_insee is not None:
            self.code_insee = code_insee
        if longitude is not None:
            self.longitude = longitude
        if latitude is not None:
            self.latitude = latitude

    @property
    def identifiant(self):
        """Gets the identifiant of this Cavites.  # noqa: E501

        Identifiant unique d'une cavité souterraine  # noqa: E501

        :return: The identifiant of this Cavites.  # noqa: E501
        :rtype: str
        """
        return self._identifiant

    @identifiant.setter
    def identifiant(self, identifiant):
        """Sets the identifiant of this Cavites.

        Identifiant unique d'une cavité souterraine  # noqa: E501

        :param identifiant: The identifiant of this Cavites.  # noqa: E501
        :type: str
        """

        self._identifiant = identifiant

    @property
    def type(self):
        """Gets the type of this Cavites.  # noqa: E501

        Type de cavité souterraine  # noqa: E501

        :return: The type of this Cavites.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Cavites.

        Type de cavité souterraine  # noqa: E501

        :param type: The type of this Cavites.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def nom(self):
        """Gets the nom of this Cavites.  # noqa: E501

        Nom de cavité souterraine  # noqa: E501

        :return: The nom of this Cavites.  # noqa: E501
        :rtype: str
        """
        return self._nom

    @nom.setter
    def nom(self, nom):
        """Sets the nom of this Cavites.

        Nom de cavité souterraine  # noqa: E501

        :param nom: The nom of this Cavites.  # noqa: E501
        :type: str
        """

        self._nom = nom

    @property
    def reperage_geo(self):
        """Gets the reperage_geo of this Cavites.  # noqa: E501

        Repération géographique de la cavité souterraine  # noqa: E501

        :return: The reperage_geo of this Cavites.  # noqa: E501
        :rtype: str
        """
        return self._reperage_geo

    @reperage_geo.setter
    def reperage_geo(self, reperage_geo):
        """Sets the reperage_geo of this Cavites.

        Repération géographique de la cavité souterraine  # noqa: E501

        :param reperage_geo: The reperage_geo of this Cavites.  # noqa: E501
        :type: str
        """

        self._reperage_geo = reperage_geo

    @property
    def region(self):
        """Gets the region of this Cavites.  # noqa: E501


        :return: The region of this Cavites.  # noqa: E501
        :rtype: Region
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this Cavites.


        :param region: The region of this Cavites.  # noqa: E501
        :type: Region
        """

        self._region = region

    @property
    def departement(self):
        """Gets the departement of this Cavites.  # noqa: E501


        :return: The departement of this Cavites.  # noqa: E501
        :rtype: Departement
        """
        return self._departement

    @departement.setter
    def departement(self, departement):
        """Sets the departement of this Cavites.


        :param departement: The departement of this Cavites.  # noqa: E501
        :type: Departement
        """

        self._departement = departement

    @property
    def code_insee(self):
        """Gets the code_insee of this Cavites.  # noqa: E501

        Identifiant unique INSEE de la commune  # noqa: E501

        :return: The code_insee of this Cavites.  # noqa: E501
        :rtype: str
        """
        return self._code_insee

    @code_insee.setter
    def code_insee(self, code_insee):
        """Sets the code_insee of this Cavites.

        Identifiant unique INSEE de la commune  # noqa: E501

        :param code_insee: The code_insee of this Cavites.  # noqa: E501
        :type: str
        """

        self._code_insee = code_insee

    @property
    def longitude(self):
        """Gets the longitude of this Cavites.  # noqa: E501

        Longitude de la commune  # noqa: E501

        :return: The longitude of this Cavites.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this Cavites.

        Longitude de la commune  # noqa: E501

        :param longitude: The longitude of this Cavites.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def latitude(self):
        """Gets the latitude of this Cavites.  # noqa: E501

        Latitude de la commune  # noqa: E501

        :return: The latitude of this Cavites.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this Cavites.

        Latitude de la commune  # noqa: E501

        :param latitude: The latitude of this Cavites.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Cavites, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Cavites):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
