# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EtatPPR(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code_etat': 'str',
        'libelle_etat': 'str'
    }

    attribute_map = {
        'code_etat': 'code_etat',
        'libelle_etat': 'libelle_etat'
    }

    def __init__(self, code_etat=None, libelle_etat=None):  # noqa: E501
        """EtatPPR - a model defined in Swagger"""  # noqa: E501
        self._code_etat = None
        self._libelle_etat = None
        self.discriminator = None
        if code_etat is not None:
            self.code_etat = code_etat
        if libelle_etat is not None:
            self.libelle_etat = libelle_etat

    @property
    def code_etat(self):
        """Gets the code_etat of this EtatPPR.  # noqa: E501

        Code de l'état d'un document PPR  # noqa: E501

        :return: The code_etat of this EtatPPR.  # noqa: E501
        :rtype: str
        """
        return self._code_etat

    @code_etat.setter
    def code_etat(self, code_etat):
        """Sets the code_etat of this EtatPPR.

        Code de l'état d'un document PPR  # noqa: E501

        :param code_etat: The code_etat of this EtatPPR.  # noqa: E501
        :type: str
        """

        self._code_etat = code_etat

    @property
    def libelle_etat(self):
        """Gets the libelle_etat of this EtatPPR.  # noqa: E501

        Libellé de l'état d'un document PPR  # noqa: E501

        :return: The libelle_etat of this EtatPPR.  # noqa: E501
        :rtype: str
        """
        return self._libelle_etat

    @libelle_etat.setter
    def libelle_etat(self, libelle_etat):
        """Sets the libelle_etat of this EtatPPR.

        Libellé de l'état d'un document PPR  # noqa: E501

        :param libelle_etat: The libelle_etat of this EtatPPR.  # noqa: E501
        :type: str
        """

        self._libelle_etat = libelle_etat

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EtatPPR, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EtatPPR):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
