# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NoPaginatedResponseTriZonageDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'results': 'int',
        'data': 'list[TriZonageDto]',
        'response_code': 'int',
        'message': 'str'
    }

    attribute_map = {
        'results': 'results',
        'data': 'data',
        'response_code': 'response_code',
        'message': 'message'
    }

    def __init__(self, results=None, data=None, response_code=None, message=None):  # noqa: E501
        """NoPaginatedResponseTriZonageDto - a model defined in Swagger"""  # noqa: E501
        self._results = None
        self._data = None
        self._response_code = None
        self._message = None
        self.discriminator = None
        if results is not None:
            self.results = results
        if data is not None:
            self.data = data
        if response_code is not None:
            self.response_code = response_code
        if message is not None:
            self.message = message

    @property
    def results(self):
        """Gets the results of this NoPaginatedResponseTriZonageDto.  # noqa: E501

        Le nombre total de résultats  # noqa: E501

        :return: The results of this NoPaginatedResponseTriZonageDto.  # noqa: E501
        :rtype: int
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this NoPaginatedResponseTriZonageDto.

        Le nombre total de résultats  # noqa: E501

        :param results: The results of this NoPaginatedResponseTriZonageDto.  # noqa: E501
        :type: int
        """

        self._results = results

    @property
    def data(self):
        """Gets the data of this NoPaginatedResponseTriZonageDto.  # noqa: E501

        Le tableau contenant la réponse du endpoint  # noqa: E501

        :return: The data of this NoPaginatedResponseTriZonageDto.  # noqa: E501
        :rtype: list[TriZonageDto]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this NoPaginatedResponseTriZonageDto.

        Le tableau contenant la réponse du endpoint  # noqa: E501

        :param data: The data of this NoPaginatedResponseTriZonageDto.  # noqa: E501
        :type: list[TriZonageDto]
        """

        self._data = data

    @property
    def response_code(self):
        """Gets the response_code of this NoPaginatedResponseTriZonageDto.  # noqa: E501

        Le code HTTP de la réponse  # noqa: E501

        :return: The response_code of this NoPaginatedResponseTriZonageDto.  # noqa: E501
        :rtype: int
        """
        return self._response_code

    @response_code.setter
    def response_code(self, response_code):
        """Sets the response_code of this NoPaginatedResponseTriZonageDto.

        Le code HTTP de la réponse  # noqa: E501

        :param response_code: The response_code of this NoPaginatedResponseTriZonageDto.  # noqa: E501
        :type: int
        """

        self._response_code = response_code

    @property
    def message(self):
        """Gets the message of this NoPaginatedResponseTriZonageDto.  # noqa: E501

        Le message d'erreur si applicable  # noqa: E501

        :return: The message of this NoPaginatedResponseTriZonageDto.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this NoPaginatedResponseTriZonageDto.

        Le message d'erreur si applicable  # noqa: E501

        :param message: The message of this NoPaginatedResponseTriZonageDto.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NoPaginatedResponseTriZonageDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NoPaginatedResponseTriZonageDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
