# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RisqueDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'present': 'bool',
        'libelle': 'str'
    }

    attribute_map = {
        'present': 'present',
        'libelle': 'libelle'
    }

    def __init__(self, present=None, libelle=None):  # noqa: E501
        """RisqueDto - a model defined in Swagger"""  # noqa: E501
        self._present = None
        self._libelle = None
        self.discriminator = None
        if present is not None:
            self.present = present
        if libelle is not None:
            self.libelle = libelle

    @property
    def present(self):
        """Gets the present of this RisqueDto.  # noqa: E501


        :return: The present of this RisqueDto.  # noqa: E501
        :rtype: bool
        """
        return self._present

    @present.setter
    def present(self, present):
        """Sets the present of this RisqueDto.


        :param present: The present of this RisqueDto.  # noqa: E501
        :type: bool
        """

        self._present = present

    @property
    def libelle(self):
        """Gets the libelle of this RisqueDto.  # noqa: E501


        :return: The libelle of this RisqueDto.  # noqa: E501
        :rtype: str
        """
        return self._libelle

    @libelle.setter
    def libelle(self, libelle):
        """Sets the libelle of this RisqueDto.


        :param libelle: The libelle of this RisqueDto.  # noqa: E501
        :type: str
        """

        self._libelle = libelle

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RisqueDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RisqueDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
