# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SupDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'adresse': 'str',
        'nom': 'str',
        'superficie': 'float',
        'geom': 'OneOfSupDtoGeom',
        'identifiant_ssp': 'str',
        'adresse_lieudit': 'str',
        'code_insee': 'str',
        'nom_commune': 'str',
        'fiche_risque': 'str',
        'statut_classification': 'str',
        'date_maj': 'str'
    }

    attribute_map = {
        'adresse': 'adresse',
        'nom': 'nom',
        'superficie': 'superficie',
        'geom': 'geom',
        'identifiant_ssp': 'identifiant_ssp',
        'adresse_lieudit': 'adresse_lieudit',
        'code_insee': 'code_insee',
        'nom_commune': 'nom_commune',
        'fiche_risque': 'fiche_risque',
        'statut_classification': 'statut_classification',
        'date_maj': 'date_maj'
    }

    def __init__(self, adresse=None, nom=None, superficie=None, geom=None, identifiant_ssp=None, adresse_lieudit=None, code_insee=None, nom_commune=None, fiche_risque=None, statut_classification=None, date_maj=None):  # noqa: E501
        """SupDto - a model defined in Swagger"""  # noqa: E501
        self._adresse = None
        self._nom = None
        self._superficie = None
        self._geom = None
        self._identifiant_ssp = None
        self._adresse_lieudit = None
        self._code_insee = None
        self._nom_commune = None
        self._fiche_risque = None
        self._statut_classification = None
        self._date_maj = None
        self.discriminator = None
        if adresse is not None:
            self.adresse = adresse
        if nom is not None:
            self.nom = nom
        if superficie is not None:
            self.superficie = superficie
        if geom is not None:
            self.geom = geom
        if identifiant_ssp is not None:
            self.identifiant_ssp = identifiant_ssp
        if adresse_lieudit is not None:
            self.adresse_lieudit = adresse_lieudit
        if code_insee is not None:
            self.code_insee = code_insee
        if nom_commune is not None:
            self.nom_commune = nom_commune
        if fiche_risque is not None:
            self.fiche_risque = fiche_risque
        if statut_classification is not None:
            self.statut_classification = statut_classification
        if date_maj is not None:
            self.date_maj = date_maj

    @property
    def adresse(self):
        """Gets the adresse of this SupDto.  # noqa: E501

        Adresse du SUP  # noqa: E501

        :return: The adresse of this SupDto.  # noqa: E501
        :rtype: str
        """
        return self._adresse

    @adresse.setter
    def adresse(self, adresse):
        """Sets the adresse of this SupDto.

        Adresse du SUP  # noqa: E501

        :param adresse: The adresse of this SupDto.  # noqa: E501
        :type: str
        """

        self._adresse = adresse

    @property
    def nom(self):
        """Gets the nom of this SupDto.  # noqa: E501

        Nom du SUP  # noqa: E501

        :return: The nom of this SupDto.  # noqa: E501
        :rtype: str
        """
        return self._nom

    @nom.setter
    def nom(self, nom):
        """Sets the nom of this SupDto.

        Nom du SUP  # noqa: E501

        :param nom: The nom of this SupDto.  # noqa: E501
        :type: str
        """

        self._nom = nom

    @property
    def superficie(self):
        """Gets the superficie of this SupDto.  # noqa: E501

        Superficie du SUP en m2  # noqa: E501

        :return: The superficie of this SupDto.  # noqa: E501
        :rtype: float
        """
        return self._superficie

    @superficie.setter
    def superficie(self, superficie):
        """Sets the superficie of this SupDto.

        Superficie du SUP en m2  # noqa: E501

        :param superficie: The superficie of this SupDto.  # noqa: E501
        :type: float
        """

        self._superficie = superficie

    @property
    def geom(self):
        """Gets the geom of this SupDto.  # noqa: E501


        :return: The geom of this SupDto.  # noqa: E501
        :rtype: OneOfSupDtoGeom
        """
        return self._geom

    @geom.setter
    def geom(self, geom):
        """Sets the geom of this SupDto.


        :param geom: The geom of this SupDto.  # noqa: E501
        :type: OneOfSupDtoGeom
        """

        self._geom = geom

    @property
    def identifiant_ssp(self):
        """Gets the identifiant_ssp of this SupDto.  # noqa: E501

        Identifiant unique du SSP  # noqa: E501

        :return: The identifiant_ssp of this SupDto.  # noqa: E501
        :rtype: str
        """
        return self._identifiant_ssp

    @identifiant_ssp.setter
    def identifiant_ssp(self, identifiant_ssp):
        """Sets the identifiant_ssp of this SupDto.

        Identifiant unique du SSP  # noqa: E501

        :param identifiant_ssp: The identifiant_ssp of this SupDto.  # noqa: E501
        :type: str
        """

        self._identifiant_ssp = identifiant_ssp

    @property
    def adresse_lieudit(self):
        """Gets the adresse_lieudit of this SupDto.  # noqa: E501

        Lieu-dit du SUP  # noqa: E501

        :return: The adresse_lieudit of this SupDto.  # noqa: E501
        :rtype: str
        """
        return self._adresse_lieudit

    @adresse_lieudit.setter
    def adresse_lieudit(self, adresse_lieudit):
        """Sets the adresse_lieudit of this SupDto.

        Lieu-dit du SUP  # noqa: E501

        :param adresse_lieudit: The adresse_lieudit of this SupDto.  # noqa: E501
        :type: str
        """

        self._adresse_lieudit = adresse_lieudit

    @property
    def code_insee(self):
        """Gets the code_insee of this SupDto.  # noqa: E501

        Code Insee de la commune  # noqa: E501

        :return: The code_insee of this SupDto.  # noqa: E501
        :rtype: str
        """
        return self._code_insee

    @code_insee.setter
    def code_insee(self, code_insee):
        """Sets the code_insee of this SupDto.

        Code Insee de la commune  # noqa: E501

        :param code_insee: The code_insee of this SupDto.  # noqa: E501
        :type: str
        """

        self._code_insee = code_insee

    @property
    def nom_commune(self):
        """Gets the nom_commune of this SupDto.  # noqa: E501

        Libellé de la commune  # noqa: E501

        :return: The nom_commune of this SupDto.  # noqa: E501
        :rtype: str
        """
        return self._nom_commune

    @nom_commune.setter
    def nom_commune(self, nom_commune):
        """Sets the nom_commune of this SupDto.

        Libellé de la commune  # noqa: E501

        :param nom_commune: The nom_commune of this SupDto.  # noqa: E501
        :type: str
        """

        self._nom_commune = nom_commune

    @property
    def fiche_risque(self):
        """Gets the fiche_risque of this SupDto.  # noqa: E501

        Lien vers la fiche risque du SUP  # noqa: E501

        :return: The fiche_risque of this SupDto.  # noqa: E501
        :rtype: str
        """
        return self._fiche_risque

    @fiche_risque.setter
    def fiche_risque(self, fiche_risque):
        """Sets the fiche_risque of this SupDto.

        Lien vers la fiche risque du SUP  # noqa: E501

        :param fiche_risque: The fiche_risque of this SupDto.  # noqa: E501
        :type: str
        """

        self._fiche_risque = fiche_risque

    @property
    def statut_classification(self):
        """Gets the statut_classification of this SupDto.  # noqa: E501

        Statut de la classification SUP  # noqa: E501

        :return: The statut_classification of this SupDto.  # noqa: E501
        :rtype: str
        """
        return self._statut_classification

    @statut_classification.setter
    def statut_classification(self, statut_classification):
        """Sets the statut_classification of this SupDto.

        Statut de la classification SUP  # noqa: E501

        :param statut_classification: The statut_classification of this SupDto.  # noqa: E501
        :type: str
        """

        self._statut_classification = statut_classification

    @property
    def date_maj(self):
        """Gets the date_maj of this SupDto.  # noqa: E501

        Date de mise à jour des données SUP  # noqa: E501

        :return: The date_maj of this SupDto.  # noqa: E501
        :rtype: str
        """
        return self._date_maj

    @date_maj.setter
    def date_maj(self, date_maj):
        """Sets the date_maj of this SupDto.

        Date de mise à jour des données SUP  # noqa: E501

        :param date_maj: The date_maj of this SupDto.  # noqa: E501
        :type: str
        """

        self._date_maj = date_maj

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SupDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SupDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
