# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Tim(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'date_transmission': 'date',
        'code_insee': 'str',
        'libelle_commune': 'str'
    }

    attribute_map = {
        'date_transmission': 'date_transmission',
        'code_insee': 'code_insee',
        'libelle_commune': 'libelle_commune'
    }

    def __init__(self, date_transmission=None, code_insee=None, libelle_commune=None):  # noqa: E501
        """Tim - a model defined in Swagger"""  # noqa: E501
        self._date_transmission = None
        self._code_insee = None
        self._libelle_commune = None
        self.discriminator = None
        if date_transmission is not None:
            self.date_transmission = date_transmission
        if code_insee is not None:
            self.code_insee = code_insee
        if libelle_commune is not None:
            self.libelle_commune = libelle_commune

    @property
    def date_transmission(self):
        """Gets the date_transmission of this Tim.  # noqa: E501

        Date de transmission  # noqa: E501

        :return: The date_transmission of this Tim.  # noqa: E501
        :rtype: date
        """
        return self._date_transmission

    @date_transmission.setter
    def date_transmission(self, date_transmission):
        """Sets the date_transmission of this Tim.

        Date de transmission  # noqa: E501

        :param date_transmission: The date_transmission of this Tim.  # noqa: E501
        :type: date
        """

        self._date_transmission = date_transmission

    @property
    def code_insee(self):
        """Gets the code_insee of this Tim.  # noqa: E501

        Identifiant unique INSEE de la commune  # noqa: E501

        :return: The code_insee of this Tim.  # noqa: E501
        :rtype: str
        """
        return self._code_insee

    @code_insee.setter
    def code_insee(self, code_insee):
        """Sets the code_insee of this Tim.

        Identifiant unique INSEE de la commune  # noqa: E501

        :param code_insee: The code_insee of this Tim.  # noqa: E501
        :type: str
        """

        self._code_insee = code_insee

    @property
    def libelle_commune(self):
        """Gets the libelle_commune of this Tim.  # noqa: E501

        Libellé de la commune  # noqa: E501

        :return: The libelle_commune of this Tim.  # noqa: E501
        :rtype: str
        """
        return self._libelle_commune

    @libelle_commune.setter
    def libelle_commune(self, libelle_commune):
        """Sets the libelle_commune of this Tim.

        Libellé de la commune  # noqa: E501

        :param libelle_commune: The libelle_commune of this Tim.  # noqa: E501
        :type: str
        """

        self._libelle_commune = libelle_commune

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Tim, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Tim):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
