# coding: utf-8

"""
    Services API Géorisques

    Description de l'API de Géorisques  # noqa: E501

    OpenAPI spec version: 1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ZonageArgile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code_exposition': 'str',
        'exposition': 'str'
    }

    attribute_map = {
        'code_exposition': 'codeExposition',
        'exposition': 'exposition'
    }

    def __init__(self, code_exposition=None, exposition=None):  # noqa: E501
        """ZonageArgile - a model defined in Swagger"""  # noqa: E501
        self._code_exposition = None
        self._exposition = None
        self.discriminator = None
        if code_exposition is not None:
            self.code_exposition = code_exposition
        if exposition is not None:
            self.exposition = exposition

    @property
    def code_exposition(self):
        """Gets the code_exposition of this ZonageArgile.  # noqa: E501


        :return: The code_exposition of this ZonageArgile.  # noqa: E501
        :rtype: str
        """
        return self._code_exposition

    @code_exposition.setter
    def code_exposition(self, code_exposition):
        """Sets the code_exposition of this ZonageArgile.


        :param code_exposition: The code_exposition of this ZonageArgile.  # noqa: E501
        :type: str
        """

        self._code_exposition = code_exposition

    @property
    def exposition(self):
        """Gets the exposition of this ZonageArgile.  # noqa: E501


        :return: The exposition of this ZonageArgile.  # noqa: E501
        :rtype: str
        """
        return self._exposition

    @exposition.setter
    def exposition(self, exposition):
        """Sets the exposition of this ZonageArgile.


        :param exposition: The exposition of this ZonageArgile.  # noqa: E501
        :type: str
        """

        self._exposition = exposition

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ZonageArgile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ZonageArgile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
